config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'

  devise_for :users

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :like_notes
    end
    collection do
      post :search
    end
  end

  resources :notes, only: [:show, :create, :edit, :update, :destroy, :new] do
    member do
      get :liking_users
    end
  end

  post '/like/:note_id' => 'likes#like', as: 'like'

  delete '/unlike/:note_id' => 'likes#unlike', as:'unlike'

  root 'home#top'
  get '/about' => 'home#about'
  get '/index' => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :note

end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  validates :title, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :validatable
  has_many :notes
  has_many :likes
  has_many :like_notes, through: :likes, source: :note
  validates :name, presence: true
  # validates :email, presence: true, uniqueness: true

  def set_image(file)
    if !file.nil?
      file_name = file.original_filename
      File.open("public/user_images/#{file_name}", 'wb'){|f| f.write(file.read)}
      self.image = file_name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  include ApplicationHelper

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  # 以下の1行は消さないでください
  def default_url_options() {privateIp: '10.0.0.176', containerPort: '3000', languageName: 'rails'}.merge(super) end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    if user_signed_in?
      @note = Note.new
      @notes = Note.all.order(created_at: :desc)
    else
      @message = "Welcome to『music share』 !!!"
      @summary = "音楽に関するいろんなことをみんなでシェアしよう"
    end
  end

  def about
  end

  def index
    @note = Note.new
    @notes = Note.all.order(created_at: :desc)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def like
    @note = Note.find(params[:note_id])
    like = current_user.likes.build(note_id: @note.id)
    like.save
  end

  def unlike
    @note = Note.find(params[:note_id])
    like = current_user.likes.find_by(note_id: @note.id)
    like.destroy
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :liking_users]
  before_action :correct_user, only: [:edit, :update]
  before_action :set_note, only: [:show, :edit, :update, :destroy, :liking_users]

  def new
    @note = Note.new
  end

  def show
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to @note, notice: "投稿が保存されました"
    else
      @notes = Note.all.order(created_at: :desc)
      render 'home/top'
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to @note, notice: "投稿が更新されました"
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to root_path
  end

  def liking_users
    @users = @note.liking_users
  end



  private

    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :content)
    end

    def correct_user
      note = Note.find(params[:id])
      if !current_user?(note.user)
        redirect_to root_path, alert: '許可されていないページです'
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!
    before_action :correct_user, only: [:edit, :update]
    before_action :set_user, only: [:show, :edit, :update, :like_notes]

  def index
    @users = User.all
  end

  def show
    @notes = @user.notes
    @title = "投稿一覧"
  end

  def edit
  end

  def update
    file = params[:user][:image]
    @user.set_image(file)
    if @user.update(user_params)
      redirect_to @user, notice: 'ユーザー情報が更新されました'
    else
      render :edit
    end
  end

  def like_notes
    @notes = @user.like_notes
    @title = "いいね！一覧"
    render :show
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email)
    end

    def correct_user
      user = User.find(params[:id])
      if !current_user?(user)
        redirect_to root_path, alert: '許可されていないページです'
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    current_user.id == user.id
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def image_for(user)
    if user.image
      image_tag "/user_images/#{user.image}", class: "profile_img"
    else
      image_tag "m_e_others_476", class: "profile_img"
    end
  end
end

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/home/about.html.erb
<h1>music shareとは？</h1>

<h3>
    音楽に関するいろんなことをシェアする場です<br><br>
    質問したり、答えたり、情報を発信したり、使い方は自由です<br><br>
    音楽に関することならジャンル・内容は問いません<br><br>
</h3>

<h4>例えば、</h4>

<p>
   ・みんなのおすすめのアーティストを教えてください。<br><br>
   ・私の好きなアルバムTOP10を発表します。NO.10 ＊＊＊ No.9 ＊＊＊ ....<br><br>
   ・現在バンドメンバーを募集中です！ドラムとベースを募集しています！ジャンルは....<br><br>
   ・最近トランペットを初めたのですがうまく吹けません。誰かコツを教えてください。<br><br>
   ・＊月＊日に、＊＊＊でライブをやります！！時間は....<br><br>
     etc....<br><br>
</p>

<h4>好きなように使ってください</h4>

app/views/home/index.html.erb
<ul class="notes">
  <h2>投稿の一覧</h2>
  <%= render @notes %>
</ul>

app/views/home/top.html.erb
<% if user_signed_in? %>
  <aside class="sidebar">
    <%= render 'notes/form' %>
  </aside>
  <ul class="notes">
    <h2>投稿の一覧</h2>
    <%= render @notes %>
  </ul>
<% else %>
  <div class="top-wrapper">
    <div class="register-wrapper">
      <h1><%= @message %></h1>
          <p><%= @summary %></p>
      <%= link_to "新規登録", new_user_registration_path, class: "btn btn-large register-btn" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>music share</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar">
      <div class="container">
        <div id="logo"><%= link_to "music share", root_path %></div>
          <% if user_signed_in? %>
            <ul class="header-right">
              <li><%= link_to "ユーザー一覧", users_path %></li>
              <li><%= link_to current_user.email, current_user %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            </ul>
          <% else %>
            <ul class="header-right">
              <li><%= link_to "概要", about_path %></li>
              <li><%= link_to "投稿一覧", index_path %></li>
              <li><%= link_to "新規登録", new_user_registration_path %></li>
              <li><%= link_to "ログイン", new_user_session_path %></li>
            </ul>
          <% end %>
      </div>
    </header>
    <div class="container">
    <p class="alert alert-success">
      <%= notice %>
    </p>
    <p class="alert alert-danger">
      <%= alert %>
    </p>
      <%= yield %>
    </div>

    <div class="container">
      <footer class="footer">
        <div class="small">
          &copy; 2017 shou, Inc.
        </div>
      </footer>
    </div>

  </body>
</html>

app/views/likes/_like_links.html.erb
<% if user_signed_in? %>
  <% if current_user.likes.find_by(note_id: note.id) %>
    <%= link_to 'いいね！を取り消す', unlike_path(note.id), method: :delete, remote: true %>
  <% else %>
    <%= link_to 'いいね！', like_path(note.id), method: :post, remote: true %>
  <% end %>
<% end %>

app/views/likes/like.js.erb
<!--render()の引数でパーシャルを呼び出し、変数noteに@noteを渡してください-->
$('#like-link').html('<%= escape_javascript(render("likes/like_links", note: @note )) %>');
$('#like-count').html('<%= @note.likes.count %>');

app/views/likes/unlike.js.erb
$('#like-link').html('<%= escape_javascript(render("likes/like_links", note: @note )) %>');
$('#like-count').html('<%= @note.likes.count %>');

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= @note.errors.count %>件のエラー:</h2>

      <ul>
        <% @note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  タイトル
  <%= f.text_field :title, { class: "form-control title-field" } %>
  内容
  <%= f.text_area :content, { class: "form-control content-field" } %>
  <%= f.submit "投稿", { class: "btn primary-btn" } %>
<% end %>

app/views/notes/_note.html.erb
<li>
  <%= image_for(note.user) %>
  <span class="user-name">
    <%= note.user.name %>
  </span>
  <span class="content">
    <%= link_to note.title, note_path(note.id) %>

    <div>
      <small>
        <%= note.likes.count %>人がいいね！といっています
      </small>
    </div>

  </span>
  <span>
    <%= note.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
  </span>
</li>

app/views/notes/edit.html.erb
<h1>投稿を編集する</h1>
<%= render 'form' %>

app/views/notes/index.html.erb
<h1>投稿の一覧</h1>
<ul class="notes">
  <% render @notes %>
</ul>

app/views/notes/liking_users.html.erb
<ul class='show-note'>
  <%= render @note %>
</ul>

<h2 class="heading">いいねしているユーザー一覧 </h2>
<ul class='user-list'>
  <!-- ここでパーシャルファイルを呼び出してください -->
  <%= render @users %>

</ul>

app/views/notes/new.html.erb
<h1>新規投稿する</h1>

<%= render 'form' %>

app/views/notes/show.html.erb
<% if user_signed_in? %>

  <p id="notice" class="alert alert_success" ><%= notice %></p>

  <h2>タイトル</h2>
  <p><%= @note.title %></p>
  <h2>内容</h2>
  <p><%= @note.content %></p>

  <div id="like-link">
    <%= render "likes/like_links", note: @note %>
  </div>

  <div>
    <small>
      <%= link_to @note.likes.count, liking_users_note_path(@note.id), id: 'like-count' %>人がいいね！といっています
    </small>
  </div>

  <% if current_user?(@note.user) %>
    <%= link_to "編集", edit_note_path(@note.id), class: "btn edit-btn" %>
    <%= link_to "削除", note_path(@note.id), method: "delete", class: "btn destroy-btn", "data-confirm" => "本当に削除しますか？" %>
  <% end %>

<% else %>

  <h2>タイトル</h2>
  <p><%= @note.title %></p>
  <h2>内容</h2>
  <p><%= @note.content %></p>

  <div id="like-link">
    <%= render "likes/like_links", note: @note %>
  </div>

  <div>
    <small>
      <%= @note.likes.count %>人がいいね！といっています
    </small>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
       <p><%= @user.errors.count %>件のエラーがあります。</p>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  名前
  <%= f.text_field :name, class: "form-control name-field" %>

  メールアドレス
  <%= f.text_field :email, class: "form-control email-field" %>

  プロフィール画像
  <%= f.file_field :image, class: "form-control image-field" %>

  <%= f.submit '保存', class: "btn primary-btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= image_for(user) %>
  <%= link_to user.name, user %> |
  <%= user.email %>
</li>

app/views/users/edit.html.erb
<h1>ユーザーの編集</h1>

<%= render 'form' %>

<%= link_to 'ユーザー一覧へ', users_path %>

app/views/users/index.html.erb
<h1 class="heading">ユーザー一覧</h1>

<ul class="user-list">
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<h1>新規ユーザー作成</h1>

<%= render 'form' %>

<%= link_to '戻る', users_path %>

app/views/users/show.html.erb
<p id="notice" class="alert alert-success"><%= notice %></p>

<aside class="sidebar">
  <section>
    <span class="label">プロフィール画像</span>
    <h3 class="user-info">
      <%= image_for(@user) %>
    </h3>
  </section>
  <section>
    <span class="label">ユーザー</span>
    <h3 class="user-info"><%= @user.name %></h3>
  </section>

  <section>
    <span class="label">メールアドレス</span>
    <h3 class="user-info"><%= @user.email %></h3>
  </section>

  <%= link_to @user.likes.count, like_notes_user_path(@user.id) %>個の投稿にいいね!しています

  <% if current_user?(@user) %>
    <section>
      <small><%= link_to 'プロフィールを編集', edit_user_path(@user) %></small>
      <small><%= link_to '新規投稿', new_note_path(@user) %></small>
    </section>
  <% end %>
</aside>

<ul class="notes">

  <h2><%= @title %></h2>

  <% render @notes %>

</ul>